# Generated by Django 4.1.7 on 2024-06-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0002_person_alter_contact_id_contact_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="person",
        ),
        migrations.AlterField(
            model_name="contact",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="Person",
        ),
    ]
